import type { AICommand, AICommandType } from './aiModels';
import type { AIStudioContext } from './AIContext';
import type { AIProvider, AIProviderResult } from './AIProvider';

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim()}\n`;
}

function handleExplainImport(ctx: AIStudioContext): AIProviderResult {
  const report = ctx.importReport;
  if (!report) {
    return {
      markdown: section(
        'Import context',
        'No import report is loaded. Run **Import** from the command bar or try the Godot sample on the launcher.',
      ),
      confidence: 'high',
      suggestions: ['Open Import report panel after detection', 'Preview Godot Import from startup'],
    };
  }

  const warningLines =
    report.warnings.length === 0
      ? 'No blocking warnings in the current report.'
      : report.warnings
          .map((w) => `- **${w.severity}** \`${w.code}\`: ${w.message}${w.remediation ? ` → ${w.remediation}` : ''}`)
          .join('\n');

  return {
    markdown: [
      section('Import summary', report.markdown.slice(0, 1200) + (report.markdown.length > 1200 ? '\n\n…' : '')),
      section(
        'Counts',
        `- Importable now: **${report.summary.importableNow}**\n- Manual migration: **${report.summary.requiresManual}**\n- Planned: **${report.summary.planned}**\n- Unsupported: **${report.summary.unsupported}**`,
      ),
      section('Warnings', warningLines),
      section(
        'Recommended next steps',
        '1. Review assets marked manual/unsupported.\n2. Run import preview before applying to workspace.\n3. Validate default scene in the viewport after import.',
      ),
    ].join('\n'),
    confidence: 'high',
  };
}

function handleBuildPlan(ctx: AIStudioContext): AIProviderResult {
  const target = ctx.buildTarget ?? 'web';
  const subs = ctx.runtimeSubsystems ?? {};
  const enabled = Object.entries(subs)
    .filter(([, v]) => v)
    .map(([k]) => k)
    .join(', ');

  return {
    markdown: [
      section(
        'Build plan draft',
        `Project **${ctx.projectName ?? 'Untitled'}** → target \`${target}\` (release recommended for distribution).`,
      ),
      section(
        'Pipeline steps',
        '1. Validate `.vyb/project.vyb.json` and default scene.\n2. Stage `scenes/`, `assets/`, `scripts/`, and materials.\n3. Emit `build-manifest.json` + `runtime/launch.config.json`.\n4. Package with target runtime (Tauri desktop / static host for web).',
      ),
      section('Runtime systems', enabled ? `Enabled at play time: ${enabled}` : 'No runtime subsystems flagged in studio.'),
      section(
        'CI alignment',
        'GitHub Actions already runs lint, tests, and `npm run build` for the studio shell. Extend with game export jobs per target when player runtime ships.',
      ),
    ].join('\n'),
    confidence: 'medium',
    suggestions: ['Switch to Build mode and run a release build', 'Verify WebGPU fallback path for web target'],
  };
}

function handleDesignDoc(ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: [
      section(
        'Design document outline',
        `# ${ctx.projectName ?? 'VYB Project'} — Design Brief\n\nGenerated by VYB Local AI (draft).`,
      ),
      section(
        'Vision',
        'Describe core fantasy, player loop, and unique mechanics. Link to reference titles and art direction.',
      ),
      section(
        'Technical pillars',
        `- Renderer: WebGPU-first viewport\n- Scripting: TypeScript + visual graphs\n- Scene format: \`.vybscene\` JSON ECS\n- Default scene: \`${ctx.defaultScene ?? 'scenes/main.vybscene'}\``,
      ),
      section(
        'Milestones',
        '1. Vertical slice scene with one mechanic.\n2. Import pipeline validation.\n3. Build + deploy to first target.',
      ),
    ].join('\n'),
    confidence: 'medium',
  };
}

function handleSceneChanges(ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: section(
      'Scene proposals',
      `Current selection: **${ctx.selectedEntityName ?? 'none'}** (${ctx.entityCount ?? 0} entities in scene).\n\n` +
        '- Add a `rigidbody` + `collider` to gameplay props for physics demos.\n' +
        '- Attach `script` components pointing at `scripts/*.ts` for play-mode behavior.\n' +
        '- Group environment meshes under an empty parent for hierarchy clarity.',
    ),
    confidence: 'medium',
    suggestions: ['Select Cube and enable Physics in Audio/Network Systems panel', 'Add On Tick behavior graph in World mode'],
  };
}

function handleRefactorScript(_ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: section(
      'Script refactor guidance',
      'Keep scripts as `export function onUpdate(ctx) { ... }` without TypeScript types in exported signatures — the bridge strips types before `new Function`.\n\n' +
        'Prefer `ctx.delta` for frame time and `ctx.entity.transform` for mutations. Avoid top-level `import` until module bundling ships.',
    ),
    confidence: 'high',
  };
}

function handleShaderNotes(_ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: section(
      'Shader graph notes',
      'The shader compiler emits WGSL fragment scaffolds. Connect **Base Color** and **Metallic** nodes before export.\n\n' +
        'Validate in viewport **Material** preview mode. WebGPU requires `@group(0) @binding` layout consistency.',
    ),
    confidence: 'medium',
  };
}

function handleUiLayout(_ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: section(
      'UI layout draft',
      'Use `uiElement` components (runtime scaffold) for HUD widgets. Suggested hierarchy:\n\n' +
        '- `HUD/TopBar` — health, objectives\n' +
        '- `HUD/Crosshair` — center reticle\n' +
        '- `Menus/Pause` — modal stack\n\n' +
        'Align with command-center plasma accents for active states.',
    ),
    confidence: 'low',
  };
}

function handleNpcBehavior(_ctx: AIStudioContext): AIProviderResult {
  return {
    markdown: section(
      'NPC behavior outline',
      '1. **Patrol** — visual graph: On Tick → Move along path.\n2. **Alert** — script: distance check to player.\n3. **Combat** — stub state machine in TypeScript until BT editor lands.',
    ),
    confidence: 'low',
    suggestions: ['Use World mode visual scripting for prototyping', 'Migrate to script when logic grows'],
  };
}

const HANDLERS: Record<AICommandType, (ctx: AIStudioContext) => AIProviderResult> = {
  explain_import_errors: handleExplainImport,
  generate_build_plan: handleBuildPlan,
  create_design_doc: handleDesignDoc,
  propose_scene_changes: handleSceneChanges,
  refactor_script: handleRefactorScript,
  create_shader_notes: handleShaderNotes,
  create_ui_layout: handleUiLayout,
  create_npc_behavior: handleNpcBehavior,
};

/**
 * On-device rule-based provider — no external API keys. Suitable for drafts and studio guidance.
 */
export class LocalAIProvider implements AIProvider {
  readonly id = 'local-rules';
  readonly displayName = 'VYB Local (rule-based)';

  async run(command: AICommand, context: AIStudioContext): Promise<AIProviderResult> {
    const handler = HANDLERS[command.type];
    if (!handler) {
      return {
        markdown: `Unknown task type: \`${command.type}\``,
        confidence: 'low',
      };
    }
    return handler(context);
  }
}
