import type { NodeGraphModel } from './NodeGraphModel';
import { findNode, getLinkedOutputPin } from './graphUtils';

export interface ShaderCompileResult {
  wgsl: string;
  surfaceColorExpression: string;
  warnings: string[];
}

/**
 * Compiles a shader data graph into a WGSL fragment color expression (Phase 5 scaffold).
 */
export class ShaderGraphCompiler {
  compile(graph: NodeGraphModel): ShaderCompileResult {
    const warnings: string[] = [];
    const outputNode = graph.nodes.find((n) => n.typeId === 'shader.output');
    if (!outputNode) {
      return {
        wgsl: '',
        surfaceColorExpression: 'vec3<f32>(0.36, 0.55, 0.94)',
        warnings: ['No Surface Output node found.'],
      };
    }

    const colorPin = outputNode.inputPins.find((p) => p.name === 'Color');
    let surfaceColorExpression = 'vec3<f32>(0.36, 0.55, 0.94)';
    if (colorPin) {
      const linked = getLinkedOutputPin(graph, colorPin.id);
      if (linked) {
        surfaceColorExpression = this.compilePin(graph, linked.nodeId, linked.name, warnings);
      }
    }

    const wgsl = `// Generated by VYB ShaderGraphCompiler
@fragment
fn fs_main() -> @location(0) vec4<f32> {
  let surfaceColor = ${surfaceColorExpression};
  return vec4<f32>(surfaceColor, 1.0);
}
`;

    return { wgsl, surfaceColorExpression, warnings };
  }

  private compilePin(graph: NodeGraphModel, nodeId: string, _outputPinName: string, warnings: string[]): string {
    const node = findNode(graph, nodeId);
    if (!node) return 'vec3<f32>(0.0)';

    switch (node.typeId) {
      case 'shader.float': {
        const v = Number(node.data?.value ?? 0);
        return `vec3<f32>(${v}, ${v}, ${v})`;
      }
      case 'shader.vec3': {
        const x = Number(node.data?.x ?? 0);
        const y = Number(node.data?.y ?? 0);
        const z = Number(node.data?.z ?? 0);
        return `vec3<f32>(${x}, ${y}, ${z})`;
      }
      case 'shader.multiply':
      case 'shader.add': {
        const aPin = node.inputPins.find((p) => p.name === 'A');
        const bPin = node.inputPins.find((p) => p.name === 'B');
        const a = aPin ? this.compileInput(graph, aPin.id, warnings) : '0.0';
        const b = bPin ? this.compileInput(graph, bPin.id, warnings) : '0.0';
        const op = node.typeId === 'shader.multiply' ? '*' : '+';
        return `vec3<f32>(${a} ${op} ${b})`;
      }
      case 'shader.combine': {
        const r = this.compileInputByName(graph, node, 'R', warnings);
        const g = this.compileInputByName(graph, node, 'G', warnings);
        const b = this.compileInputByName(graph, node, 'B', warnings);
        return `vec3<f32>(${r}, ${g}, ${b})`;
      }
      default:
        warnings.push(`Unsupported shader node: ${node.typeId}`);
        return 'vec3<f32>(1.0, 0.0, 1.0)';
    }
  }

  private compileInput(graph: NodeGraphModel, inputPinId: string, warnings: string[]): string {
    const linked = getLinkedOutputPin(graph, inputPinId);
    if (!linked) return '0.0';
    const expr = this.compilePin(graph, linked.nodeId, linked.name, warnings);
    if (expr.startsWith('vec3')) return `(${expr}).x`;
    return expr;
  }

  private compileInputByName(
    graph: NodeGraphModel,
    node: { inputPins: { id: string; name: string }[] },
    pinName: string,
    warnings: string[],
  ): string {
    const pin = node.inputPins.find((p) => p.name === pinName);
    if (!pin) return '0.0';
    return this.compileInput(graph, pin.id, warnings);
  }
}
